# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Security Consult
description: >
  Security Consult, NC, Security Consult and Investigations is a Charlotte, North Carolina based security consulting and private investigative service
about: > # this means to ignore newlines until "baseurl:"
  <h2><strong>ZeroFour</strong> by HTML5 UP</h2>
  <p>Hi! This is <strong>ZeroFour</strong>, a free, fully responsive HTML5 site template by <a href="http://n33.co/">AJ</a> for <a href="http://html5up.net/">HTML5 UP</a>.
  It's <a href="http://html5up.net/license/">Creative Commons Attribution</a> licensed so use it for any personal or commercial project (just credit us for the design!).</p>
  <a href="#" class="button alt icon fa-arrow-circle-right">Learn More</a>
baseurl: "/securityconsult" # the subpath of your site, e.g. /blog
keywords: ['private investigator', 'alarm installer' 'home security', 'honeywell', 'GE', 'DSC', 'Ademco', 'home security systems', 'home security system', 'wireless home security system', 'home security camera', 'wireless home security', 'home security alarms', 'home theater', 'charlotte', 'alarm system', 'police priority', 'personal protection', 'burglary systems']
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

collections:
  home_security:
    output: true
    permalink: /home-security/:path/
  business_security:
    output: true
    permalink: /business-security/:path/
  investigations:
    output: true
    permalink: /investigations/:path/
  manuals:
    output: true



header-links:
  - title: Home
    url: /
  - title: Left sidebar
    url: /left-sidebar
  - title: Right Sidebar
    url: /right-sidebar
  - title: No Sidebar
    url: /no-sidebar
dropdown:
  - title: Lorem ipsum dolor
    url: \#
  - title: Magna phasellus
    url: \#
  - title: Veroeros feugiat
    url: \#

filler:
  - title: Burglar Alarm Systems
    url: /burglar-alarms/
  - title: Cellular Backup
    url: /cellular-backup/
  - title: Fire Alarm Systems
    url: /fire-alarm-systems/
  - title: Home Alarm Monitoring
    url: /home-alarm-monitoring/
  - title: Home Camera Systems
    url: /home-camera-systems/
  - title: Smoke Alarm Systems
    url: /smoke-alarm-systems/
  - title: Transfer you monitoring
    url: /transfer-your-monitoring/


even-more-filler:
  - title: Domestic Infidelity
    url: \#
  - title: Child Custody/Visitation
    url: \#
  - title: Insurance Fraud
    url: \#


more-filler:
  - title: Access Control Systems
    url: \#
  - title: Alarm Monitoring & Cell Back UP
    url: \#
  - title: Environmental Protection
    url: \#
  - title: Fire Alarm Systems
    url: \#
  - title: Intrusion Detection
    url: \#
  - title: IP Video Surveillance
    url: \#
  - title: Transfer your monitoring
    url: \#
